# Generated by Django 5.2.3 on 2025-07-15 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='Blog',
        ),
    ]
